In [1]:
import pandas as pd

crm = pd.read_csv("data/crm1.csv", nrows=5)
device = pd.read_csv("data/device1.csv", nrows=5)
rev = pd.read_csv("data/rev1.csv", nrows=5)

print("CRM Columns:")
print(crm.columns.tolist())

print("\nDEVICE Columns:")
print(device.columns.tolist())

print("\nREVENUE Columns:")
print(rev.columns.tolist())

FileNotFoundError: [Errno 2] No such file or directory: 'data/crm1.csv'

In [2]:
import os

print("Current Folder:")
print(os.getcwd())

print("\nFiles and Folders:")
print(os.listdir())

Current Folder:
C:\Users\frans\OneDrive\Desktop\Telecom_Bill_Prediction_System

Files and Folders:
['.git', '.ipynb_checkpoints', 'app.py', 'data', 'model', 'notebook', 'outputs', 'requirements.txt', 'static', 'telecom_iot_analysis.ipynb', 'templates']

In [3]:
import os

print(os.listdir("data"))

['archive (4)', 'WA_Fn-UseC_-Telco-Customer-Churn.csv']

In [4]:
import pandas as pd

crm = pd.read_csv(
    "data/archive (4)/crm1.csv",
    nrows=5
)

device = pd.read_csv(
    "data/archive (4)/device1.csv",
    nrows=5
)

rev = pd.read_csv(
    "data/archive (4)/rev1.csv",
    nrows=5
)

print("CRM Columns:")
print(crm.columns.tolist())

print("\nDEVICE Columns:")
print(device.columns.tolist())

print("\nREVENUE Columns:")
print(rev.columns.tolist())

CRM Columns:
['msisdn', 'gender', 'year_of_birth', 'system_status', 'mobile_type', 'value_segment']

DEVICE Columns:
['msisdn', 'imei_tac', 'brand_name', 'model_name', 'os_name', 'os_vendor']

REVENUE Columns:
['msisdn', 'week_number', 'revenue_usd']

In [5]:
import pandas as pd

for chunk in pd.read_csv(
    "data/archive (4)/rev1.csv",
    chunksize=50000
):
    print("Chunk Shape:", chunk.shape)
    print(chunk.head())
    break

Chunk Shape: (50000, 3)
                             msisdn  week_number  revenue_usd
0  66e94d24d8e0d5776a8a6b694782eff0           26    20.265621
1  66e94d24d8e0d5776a8a6b694782eff0           34     5.361164
2  66e94d24d8e0d5776a8a6b694782eff0           31    18.181347
3  66e94d24d8e0d5776a8a6b694782eff0           35    16.857391
4  66e94d24d8e0d5776a8a6b694782eff0           24    14.392326

In [6]:
# Import pandas library
import pandas as pd

# Empty list to store processed chunk summaries
customer_revenue = []

# Read revenue dataset in chunks of 50,000 rows
# This is done to handle large datasets efficiently
for chunk in pd.read_csv(
    "data/archive (4)/rev1.csv",
    chunksize=50000
):

    # Group records by customer (msisdn)
    # and calculate revenue statistics
    summary = chunk.groupby("msisdn").agg({
        "revenue_usd": ["mean", "max", "min", "sum"]
    })

    # Rename columns for readability
    summary.columns = [
        "avg_revenue",
        "max_revenue",
        "min_revenue",
        "total_revenue"
    ]

    # Convert grouped index back to a normal column
    summary.reset_index(inplace=True)

    # Store chunk summary in a list
    customer_revenue.append(summary)

    # Print progress message
    print("Processed Chunk Successfully")

    # Process only first chunk for testing
    break

Processed Chunk Successfully

In [7]:
# Display first 5 customers from processed chunk
customer_revenue[0].head()

,msisdn,avg_revenue,max_revenue,min_revenue,total_revenue
0,00034db79d29743dceb391011412db4d,11.215501,20.878741,1.523992,134.586011
1,001506d782c088fe583d770712533647,12.745695,21.937263,3.584502,178.439736
2,001dd26073ac35e338347a75abfcf4e1,12.886252,22.924289,1.698672,180.407533
3,002859b8869af85cf6757769428a5f7c,7.178604,15.466294,2.372449,43.071622
4,0032560139c078af6a5d3c01154cb586,13.223696,19.148990,3.383264,145.460655

In [10]:
# Import pandas library
import pandas as pd

# Empty list to store processed chunk summaries
customer_revenue = []

# Read revenue dataset in chunks
for chunk in pd.read_csv(
    "data/archive (4)/rev1.csv",
    chunksize=50000
):

    # Calculate revenue statistics for each customer
    summary = chunk.groupby("msisdn").agg({
        "revenue_usd": ["mean", "max", "min", "sum"]
    })

    # Rename columns
    summary.columns = [
        "avg_revenue",
        "max_revenue",
        "min_revenue",
        "total_revenue"
    ]

    # Convert index to column
    summary.reset_index(inplace=True)

    # Store processed chunk
    customer_revenue.append(summary)

# Combine all chunk summaries into one dataframe
revenue_summary = pd.concat(
    customer_revenue,
    ignore_index=True
)

print("Revenue Summary Shape:")
print(revenue_summary.shape)
# Read the large revenue dataset in chunks
# Generate revenue statistics for each customer
# Combine all processed chunks into a single dataframe
# This approach reduces memory usage and supports large-scale telecom data processing

Revenue Summary Shape:
(152237, 5)

In [11]:
# Display first 5 rows
revenue_summary.head()

,msisdn,avg_revenue,max_revenue,min_revenue,total_revenue
0,00034db79d29743dceb391011412db4d,11.215501,20.878741,1.523992,134.586011
1,001506d782c088fe583d770712533647,12.745695,21.937263,3.584502,178.439736
2,001dd26073ac35e338347a75abfcf4e1,12.886252,22.924289,1.698672,180.407533
3,002859b8869af85cf6757769428a5f7c,7.178604,15.466294,2.372449,43.071622
4,0032560139c078af6a5d3c01154cb586,13.223696,19.148990,3.383264,145.460655

In [14]:
# Load CRM customer profile dataset
crm = pd.read_csv(
    "data/archive (4)/crm1.csv"
)

# Load device information dataset
device = pd.read_csv(
    "data/archive (4)/device1.csv"
)

# Display dataset shapes
print("CRM Shape:", crm.shape)

print("Device Shape:", device.shape)

CRM Shape: (13627493, 6)
Device Shape: (2440100, 6)

In [15]:
# Read revenue dataset size

rev_sample = pd.read_csv(
    "data/archive (4)/rev1.csv"
)

print("Revenue Shape:")
print(rev_sample.shape)

Revenue Shape:
(1704601, 3)

In [16]:
# Check final revenue summary shape

print("Revenue Summary Shape:")
print(revenue_summary.shape)

# Check unique customers

print("\nUnique Customers:")
print(revenue_summary["msisdn"].nunique())

Revenue Summary Shape:
(152237, 5)

Unique Customers:
143731

In [17]:
# Combine duplicate customers created across chunks
# After processing multiple chunks, the same customer may appear
# in more than one chunk. Therefore, a final aggregation step is
# performed to create one record per customer.
final_revenue = revenue_summary.groupby("msisdn").agg({
    "avg_revenue": "mean",
    "max_revenue": "max",
    "min_revenue": "min",
    "total_revenue": "sum"
}).reset_index()

print("Final Revenue Shape:")
print(final_revenue.shape)

print("\nUnique Customers:")
print(final_revenue["msisdn"].nunique())

Final Revenue Shape:
(143731, 5)

Unique Customers:
143731

In [18]:
# Create a set of customer IDs from revenue table
# A set provides very fast lookup performance
# Extract all unique customer identifiers from the
# revenue summary table. These customers will be used
# to filter the large CRM dataset.
revenue_customers = set(
    final_revenue["msisdn"]
)

print("Revenue Customers:")
print(len(revenue_customers))

Revenue Customers:
143731

In [19]:
# Display first few customer IDs

list(revenue_customers)[:5]

['a62ca91f5631cc47e3a7c89489770af1',
 '2dba2430a222bf5ed169f4994635582f',
 '04d2e99e2b742f6bc60933a1dbeaab56',
 '682e4779271092e89214fd66f7076d5a',
 '980bca5df4d66aa28fd48f185686f4b8']

In [20]:
# Import pandas
import pandas as pd

# Store filtered CRM records
crm_filtered = []

# Read CRM dataset in chunks
for chunk in pd.read_csv(
    "data/archive (4)/crm1.csv",
    chunksize=50000
):

    # Keep only customers that exist
    # in the revenue table
    filtered_chunk = chunk[
        chunk["msisdn"].isin(revenue_customers)
    ]

    # Store matching customers
    crm_filtered.append(filtered_chunk)

# Combine all matching CRM chunks
crm_final = pd.concat(
    crm_filtered,
    ignore_index=True
)

print("Filtered CRM Shape:")
print(crm_final.shape)
# Read CRM dataset in chunks to avoid loading
# 13.6 million records into memory at once

# Filter only customers that appear in
# the revenue summary table

# Combine matching CRM records into
# a final customer profile dataset

Filtered CRM Shape:
(122086, 6)

In [21]:
# Read Device dataset in chunks
# Keep only customers present in revenue summary
# Store matching device records

# Combine all filtered chunks into a single dataset
device_filtered = []

for chunk in pd.read_csv(
    "data/archive (4)/device1.csv",
    chunksize=50000
):

    filtered_chunk = chunk[
        chunk["msisdn"].isin(revenue_customers)
    ]

    device_filtered.append(filtered_chunk)

# Combine filtered device records
device_final = pd.concat(
    device_filtered,
    ignore_index=True
)

print("Filtered Device Shape:")
print(device_final.shape)

Filtered Device Shape:
(20521, 6)

In [22]:
# Merge revenue summary with CRM data
# Merge customer revenue features with CRM profile data
# using msisdn as the common customer identifier
final_df = pd.merge(
    final_revenue,
    crm_final,
    on="msisdn",
    how="left"
)

print("After CRM Merge:")
print(final_df.shape)

After CRM Merge:
(168466, 10)

In [23]:
# Merge device information
# Merge device information to create a unified
# telecom customer dataset containing revenue,
# customer profile and device attributes
final_df = pd.merge(
    final_df,
    device_final,
    on="msisdn",
    how="left"
)

print("Final Dataset Shape:")
print(final_df.shape)

Final Dataset Shape:
(169028, 15)

In [24]:
# Display first 5 rows

final_df.head()

,msisdn,avg_revenue,max_revenue,min_revenue,total_revenue,gender,year_of_birth,system_status,mobile_type,value_segment,imei_tac,brand_name,model_name,os_name,os_vendor
0,00000b6bff59445804c19425bf61971a,11.699268,20.828212,2.217922,152.090481,Male,1994.0,ACTIVE,Prepaid,Tier_3,c395eac49569e6741faf98284aef725c,SYMPHONY,B13,NaN,NaN
1,00003cd919b7dbc0e70bf7983e1eb80e,11.211503,20.379914,3.178721,156.961039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00012aea7c3752d50ce798153ab43e13,12.485113,19.858473,4.810481,174.791576,NaN,1989.0,ACTIVE,Prepaid,Tier_3,NaN,NaN,NaN,NaN,NaN
3,00012aea7c3752d50ce798153ab43e13,12.485113,19.858473,4.810481,174.791576,Female,1989.0,ACTIVE,Prepaid,Tier_3,NaN,NaN,NaN,NaN,NaN
4,00018dada4ec594e9e7bd997c6ad512b,9.386722,23.743192,1.017281,112.640666,Male,1972.0,ACTIVE,Prepaid,Tier_3,NaN,NaN,NaN,NaN,NaN

In [25]:
# Check customer duplication after CRM merge
# Check how many duplicate customer records exist
# after merging revenue and CRM datasets
print("Total Rows:", len(final_df))

print("Unique Customers:", final_df["msisdn"].nunique())

print(
    "Duplicate Rows:",
    len(final_df) - final_df["msisdn"].nunique()
)

Total Rows: 169028
Unique Customers: 143731
Duplicate Rows: 25297

In [26]:
# Keep only one record per customer

crm_final_clean = crm_final.drop_duplicates(
    subset="msisdn"
)

print("CRM Clean Shape:")
print(crm_final_clean.shape)

CRM Clean Shape:
(97351, 6)

In [29]:
# Merge revenue and cleaned CRM data

final_df = pd.merge(
    final_revenue,
    crm_final_clean,
    on="msisdn",
    how="left"
)

print("After Clean CRM Merge:")
print(final_df.shape)

After Clean CRM Merge:
(143731, 10)

In [28]:
# Remove duplicate device records
# Keep one device profile per customer

device_final_clean = device_final.drop_duplicates(
    subset="msisdn"
)

print("Device Clean Shape:")
print(device_final_clean.shape)

Device Clean Shape:
(20044, 6)

In [30]:
# Merge device information with final dataset

final_df = pd.merge(
    final_df,
    device_final_clean,
    on="msisdn",
    how="left"
)

print("Final Dataset Shape:")
print(final_df.shape)

print("\nUnique Customers:")
print(final_df["msisdn"].nunique())

Final Dataset Shape:
(143731, 15)

Unique Customers:
143731

In [31]:
# Check missing values in final dataset

print(final_df.isnull().sum())

msisdn                0
avg_revenue           0
max_revenue           0
min_revenue           0
total_revenue         0
gender            64256
year_of_birth     46382
system_status     46380
mobile_type       46380
value_segment     46380
imei_tac         123687
brand_name       123914
model_name       123914
os_name          129063
os_vendor        128888
dtype: int64

In [32]:
# Create customer age from year of birth

final_df["age"] = 2025 - final_df["year_of_birth"]

final_df[[
    "year_of_birth",
    "age"
]].head()

   year_of_birth   age
0         1994.0  31.0
1            NaN   NaN
2         1989.0  36.0
3         1972.0  53.0
4         1970.0  55.0

In [33]:
# Fill missing categorical values

final_df["gender"] = final_df["gender"].fillna("Unknown")

final_df["system_status"] = final_df["system_status"].fillna("Unknown")

final_df["mobile_type"] = final_df["mobile_type"].fillna("Unknown")

final_df["value_segment"] = final_df["value_segment"].fillna("Unknown")

final_df["brand_name"] = final_df["brand_name"].fillna("Unknown")

final_df["model_name"] = final_df["model_name"].fillna("Unknown")

final_df["os_name"] = final_df["os_name"].fillna("Unknown")

final_df["os_vendor"] = final_df["os_vendor"].fillna("Unknown")

In [34]:
# Create revenue drop percentage
# Identify customers whose revenue has significantly
# dropped compared to their historical performance.
final_df["revenue_drop"] = (
    final_df["max_revenue"]
    - final_df["avg_revenue"]
)

# Calculate threshold using top 10% revenue drops

threshold = final_df["revenue_drop"].quantile(0.90)

print("Revenue Drop Threshold:")
print(threshold)

Revenue Drop Threshold:
11.173708739716906

In [35]:
# Create risk labels
# Customers with large revenue drops are classified
# as High Risk customers.
final_df["risk_level"] = final_df["revenue_drop"].apply(
    lambda x:
    "High Risk"
    if x > threshold
    else "Normal"
)

print(final_df["risk_level"].value_counts())

risk_level
Normal       129358
High Risk     14373
Name: count, dtype: int64

In [36]:
# Create outreach customer segment
# High Risk customers are marked as Outreach Customers
# so they can be targeted with retention campaigns.
final_df["customer_segment"] = final_df["risk_level"].apply(
    lambda x:
    "Outreach Customer"
    if x == "High Risk"
    else "Regular Customer"
)

print(final_df["customer_segment"].value_counts())

customer_segment
Regular Customer     129358
Outreach Customer     14373
Name: count, dtype: int64

In [37]:
# Identify enterprise customers
# Customers in the top 25% of total revenue
# are classified as Enterprise Customers.
final_df["enterprise_customer"] = (
    (final_df["total_revenue"] > final_df["total_revenue"].quantile(0.75))
)

print(final_df["enterprise_customer"].value_counts())

enterprise_customer
False    107798
True      35933
Name: count, dtype: int64

In [38]:
# Function to recommend offers
# Generate personalized retention offers
# based on customer risk and value segment.
def recommend_offer(row):

    if row["risk_level"] == "High Risk":

        if row["value_segment"] == "Tier_1":
            return "Premium Loyalty Offer"

        elif row["value_segment"] == "Tier_2":
            return "Revenue Retention Offer"

        else:
            return "Discount Retention Offer"

    else:
        return "No Offer Needed"


# Apply recommendation logic

final_df["recommended_offer"] = final_df.apply(
    recommend_offer,
    axis=1
)

print(final_df["recommended_offer"].value_counts())

recommended_offer
No Offer Needed             129358
Discount Retention Offer     14373
Name: count, dtype: int64

In [39]:
# Generate personalized email text
# Generate automated customer emails
# based on risk level and recommended offer.
def create_email(row):

    if row["risk_level"] == "High Risk":

        return (
            f"Dear Customer, "
            f"We noticed a decline in your recent revenue activity. "
            f"As a valued customer, we are offering you a "
            f"{row['recommended_offer']}. "
            f"Thank you for choosing our telecom services."
        )

    else:

        return (
            "Thank you for being a valued customer."
        )


# Create email column

final_df["email_text"] = final_df.apply(
    create_email,
    axis=1
)

print(final_df[[
    "risk_level",
    "recommended_offer",
    "email_text"
]].head())

  risk_level         recommended_offer  \
0     Normal           No Offer Needed
1     Normal           No Offer Needed
2     Normal           No Offer Needed
3  High Risk  Discount Retention Offer
4     Normal           No Offer Needed

                                          email_text
0             Thank you for being a valued customer.
1             Thank you for being a valued customer.
2             Thank you for being a valued customer.
3  Dear Customer, We noticed a decline in your re...
4             Thank you for being a valued customer.

In [40]:
# Select final output columns
# Create final customer scorecard containing
# revenue metrics, risk labels, offers and emails.
final_scorecard = final_df[[
    "msisdn",
    "avg_revenue",
    "total_revenue",
    "risk_level",
    "customer_segment",
    "enterprise_customer",
    "recommended_offer",
    "email_text"
]]

print(final_scorecard.shape)

final_scorecard.head()

(143731, 8)

,msisdn,avg_revenue,total_revenue,risk_level,customer_segment,enterprise_customer,recommended_offer,email_text
0,00000b6bff59445804c19425bf61971a,11.699268,152.090481,Normal,Regular Customer,False,No Offer Needed,Thank you for being a valued customer.
1,00003cd919b7dbc0e70bf7983e1eb80e,11.211503,156.961039,Normal,Regular Customer,False,No Offer Needed,Thank you for being a valued customer.
2,00012aea7c3752d50ce798153ab43e13,12.485113,174.791576,Normal,Regular Customer,True,No Offer Needed,Thank you for being a valued customer.
3,00018dada4ec594e9e7bd997c6ad512b,9.386722,112.640666,High Risk,Outreach Customer,False,Discount Retention Offer,"Dear Customer, We noticed a decline in your re..."
4,0001eea3e887f9ad213d6de124c119fb,7.282734,50.979139,Normal,Regular Customer,False,No Offer Needed,Thank you for being a valued customer.

In [41]:
# Save final scorecard
# Export final scorecard for dashboard integration.
final_scorecard.to_csv(
    "outputs/final_customer_scorecard.csv",
    index=False
)

print("Final Scorecard Saved Successfully")

Final Scorecard Saved Successfully

In [42]:
import pandas as pd

df = pd.read_csv(
    "outputs/final_customer_scorecard.csv"
)

print(df.shape)

df.head()

(143731, 8)

,msisdn,avg_revenue,total_revenue,risk_level,customer_segment,enterprise_customer,recommended_offer,email_text
0,00000b6bff59445804c19425bf61971a,11.699268,152.090481,Normal,Regular Customer,False,No Offer Needed,Thank you for being a valued customer.
1,00003cd919b7dbc0e70bf7983e1eb80e,11.211503,156.961039,Normal,Regular Customer,False,No Offer Needed,Thank you for being a valued customer.
2,00012aea7c3752d50ce798153ab43e13,12.485113,174.791576,Normal,Regular Customer,True,No Offer Needed,Thank you for being a valued customer.
3,00018dada4ec594e9e7bd997c6ad512b,9.386722,112.640666,High Risk,Outreach Customer,False,Discount Retention Offer,"Dear Customer, We noticed a decline in your re..."
4,0001eea3e887f9ad213d6de124c119fb,7.282734,50.979139,Normal,Regular Customer,False,No Offer Needed,Thank you for being a valued customer.

In [43]:
df.columns.tolist()

['msisdn',
 'avg_revenue',
 'total_revenue',
 'risk_level',
 'customer_segment',
 'enterprise_customer',
 'recommended_offer',
 'email_text']